# Generated by Django 3.1.1 on 2020-10-03 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_endpoint', models.URLField(help_text='Push Service Endpoint', unique=True)),
                ('p256dh', models.CharField(help_text='p256 key', max_length=256)),
                ('auth', models.CharField(help_text='Auth key', max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
